/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndresFWilT
 * @author Niko_Andrade
 * @author JohanM - Chetos
 */
public class Tabla2 extends javax.swing.JFrame {
    
    /**
     * Creates new form Tabla2
     */
    String[][] Matriz;
    String[] Precedentes;
    String [] Actividad;
    int n;
    
    
    //Tabla 2; es decir, tabla final con todos los datos
    
    public Tabla2(String tabla [][],int N) {
        this.setTitle("Calculo ruta critica");
        this.setLocationRelativeTo(this);
        this.n =N;
        Matriz  = new String [n][9];
        this.Matriz = tabla;
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
    }
    
    public void CreacionTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(n);
        modelo.setColumnCount(9);
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < 9; j++) {
                jTable1.setModel(modelo);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bGrafo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {
            },
            new String[] {
                "Actividad", "Precedentes", "Tiempo", "IC" ,"TC" ,"IL" ,"TL","Holgura","Critico"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.setRowSelectionAllowed(true);
        CreacionTabla();

        for (int i=0;i<n;i++) {
            for (int j=0;j<9;j++) {
                jTable1.setValueAt(Matriz[i][j], i, j);
            }
        }

        jTable1.setRowSelectionAllowed(false);
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        bGrafo.setText("Grafo");
        bGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(bGrafo)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bGrafo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGrafoActionPerformed
        Grafico g = new Grafico(Matriz,n);
        g.setVisible(true);
    }//GEN-LAST:event_bGrafoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGrafo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
